dist: trusty
language: node_js
node_js:
- "8"
cache:
  directories:
  - ~/.cache
before_script:
  - npm install -g httpserver
  - npm run custom-build
  - cd dist && httpserver -p 8080 &
script:
  - npx cypress run
deploy:
  provider: surge
  skip_cleanup: true
  domain: hotelbooking.surge.sh
  project: ./dist
  on:
    branch: master
